### ISSUE TITLE
Customize the content and format of the forum notification emails

### ISSUE THREAD

**Issue by rgilman** [ContextInstitute/brightfuturecommons#25]
This will require a deep reverse-engineering dive into the buddypress-group-email-subscription plugin.

We have four types of emails to work with
- Immediate for every post in a group
- Immediate for every new topic in a group
- Daily Digest, which I think can include posts from multiple groups
- Weekly Summary, which I also think can include posts from multiple groups

I'd like us to be able to 
- customize the visual design of each type
- control how much of each post is included in each type of email, i.e. is it the whole thing or an excerpt?
- for the immediate emails, included the poster's name in the from name, like github does
- control whether group activities other than posts are included

These notifications are core to how well the whole system will work. We need to master them and thus also master this plugin.

**Comment by SteveMccollough** [comment]
![image](https://user-images.githubusercontent.com/90698156/154122393-db1663d6-21f6-4926-acab-5fdb7fc8974c.png)
Here is the current format of the Daily Digest trimmed for length, note multiple group summaries.  The current system reports group messages, timeline additions, image uploads, file uploads, and added Documents (Docs).

If an Upload or Photo includes a caption, the email generated uses the caption, otherwise the email generates a blank field.  The digest version here demonstrates this with entry one and two from "Steve" with a photo - first uploaded without description and then with description.  The BuddyBoss version of Daily email leaves a more obvious unfiled blank area seen below.

Correcting this could be accomplished by eliminating file and image uploads from email notifications or providing a default caption when one is not provided.  This is not a problem on the timeline as the actual file is visually added to the feed.
![image](https://user-images.githubusercontent.com/90698156/154125114-49ecfdde-d03f-4eb3-8cc6-6b916a8cc51e.png)

**Comment by rgilman** [comment]
This is the next big project I'll be working on. In my investigations so far, it looks like we need to make some significant structural changes to the way the buddypress-group-email-subscription plugin works. So I've decided to fork it. CI now has a new repository:[bfc-group-email-subscription](https://github.com/ContextInstitute/bfc-group-email-subscription). 

I hope to dive into this in the coming week.

**Comment by rgilman** [comment]
This is now complete via the bfc-group-email-subscription plugin, which is a fork of the buddypress-group-email-subscription plugin. The new plugin has its own repo [here](https://github.com/ContextInstitute/bfc-ges).

I have the plugin, logo image file and updated email template posts installed and working on com.context.org.
